### ISSUE TITLE
Add rails_12factor gem to the generated Gemfile

### ISSUE THREAD

**Issue by arturopuente** [platanus/potassium#43]

**Comment by blackjid** [comment]
Why do we need this gem added @arturo?? 
We are already adding the `rails_stdout_logging`.

Also since rails 4.2 the `config.serve_static_assets` is set to `ENV['RAILS_SERVE_STATIC_FILES'].present?` and heroku adds that envirnmental varibale by default.
https://devcenter.heroku.com/changelog-items/617

I think we don't need the rails_12factor gem...

**Comment by arturopuente** [comment]
I didn't know the `serve_static_assets` was already handled by Heroku already.

Currently `rails_stdout_logging` is added to the development and test group, so it doesn't really affect the heroku setup when the project is created. Instead of adding the `rails_12factor` gem, I'm moving `rails_stdout_logging` to the `production` group.

**Comment by blackjid** [comment]
thanks @arturopuente
